### ISSUE TITLE
put application in full-screen mode

### ISSUE THREAD

**Issue by igalic** [babydots/babydots#24]
… so that when i hand this (involuntarily) to my toddler, she can do slightly less damage

**Comment by pserwylo** [comment]
Ah, great point. Thanks for the recommendation. I did contemplate this originally, but our use case is always the phone at a distance (e.g. leaning against the wall while she is in a cot). However I can see that others may be more likely to touch and interact. 

I think the solution to this is probably:
* Add a menu item to the bottom left menu: "Lock"
* When selected, the phone can go into "[Sticky Immersive](https://developer.android.com/training/system-ui/immersive#sticky-immersive)" mode, which prevents even hitting the home or back button. Upon tapping the back or home button, a message is shown saying something like "You are in immersive mode, to return to normal, hold down the back button". This is used by the [PianOli](https://github.com/nicolasbrailo/PianOli) app which is specifically designed for user interaction from toddlers and works well.

It would be nice to have some more reasonable way to leave this immersive mode though, because it sometimes is not particularly obvious. Perhaps it hides the action bar, the main button, and replaces an unlock icon in the bottom right. Then when the user interacts with this button in some way that a baby probably wouldn't accidentally do, then we can remove it from immersive mode.

**Comment by igalic** [comment]
yeah, this is particularly tricky when the buttons are actually disabled by default, like in android 10, which only uses gestures

this is extra confusing in horizontal mode, PianOli's default.

**Comment by pserwylo** [comment]
I'm leaning towards something similar to how you enable development mode on Android. Since about Android 4 you have to click on the build number in "About Phone" and it shows a brief message saying "Press the button 5 more times to become a developer". We could have a message appear when you tap the unlock button saying "Press unlock 5 more times quickly to unlock." and if you don't do it within a second or so, it resets the counter.

It will never be perfect, but that strikes me as a nice compromise between usability and safety.

Thoughts?

**Comment by igalic** [comment]
if i understand you correctly, 
then this might get in the way:

![Screenshot_20201102-092246](https://user-images.githubusercontent.com/497249/97845582-07494000-1ced-11eb-83e3-cf6b2637b489.jpg)

**Comment by pserwylo** [comment]
Hmm, so each phone will have their own gestures that may override any sort of screen lock, I guess our hands are tied for that. This is what I have in mind so far (though I think I'll probably move it to the top menu to avoid crowding the customization menu):

https://i.imgur.com/BU2xLoP.mp4

**Comment by pserwylo** [comment]
Okay, final screenshots of the implementation to be released in v1.4.0 (noting that the implementation of "Sticky Immersive" mode differs from device to device - this screenshot is from my emulator - but the "Touch to unlock" is completely custom for this app and we have full control over):

![Screenshot_1604615550](https://user-images.githubusercontent.com/248565/98236258-2c70d380-1fb7-11eb-9560-3d5651694651.png) ![Screenshot_1604615555](https://user-images.githubusercontent.com/248565/98236275-34307800-1fb7-11eb-8c02-537fbad97e2e.png) ![Screenshot_1604615561](https://user-images.githubusercontent.com/248565/98236280-372b6880-1fb7-11eb-98cc-9116a79d5abe.png) ![Screenshot_1604615563](https://user-images.githubusercontent.com/248565/98236288-3b578600-1fb7-11eb-8bcc-db18f04fb026.png)

**Comment by pserwylo** [comment]
Thanks again for all your input! Once released (in a week or so because we'll wait for any kind translators to provide translated strings for this feature), please do come back and let me know what you think.
