### ISSUE TITLE
Rotating screen unlocks controls

### ISSUE THREAD

**Issue by yamatt** [babydots/babydots#40]
When in lock/pin mode if you rotate the device and the screen rotates you regain full control of the app  such as the top buttons

**Comment by pserwylo** [comment]
Ah, good pick up! That could be dangerous for parents if the baby unlocks the app and then does bad things! I'll try and get a fix pushed for this so that it doesn't rotate when in the locked mode.

**Comment by pserwylo** [comment]
Change pushed to master. I typically wait a few days to a week before tagging the release (which then may take another week for F-Droid to build and release). This is so that translators have an opportunity to translate the changelog (or more importantly any changes to the app - though there are no changes in this fix). I'll comment back here as the process moves forward, thanks for your patience.

**Comment by yamatt** [comment]
Got the update from f-droid. Thanks for fixing it so fast and the nod in the release notes. Although it was my son who found the bug 😉

**Comment by pserwylo** [comment]
Haha, thanks for coming back to let us know that it works as expected. Hope your son didn't cause any damage (e.g. [order any random online goods]) while taking control!
