### ISSUE TITLE
Data loss while using the app (music stops playing after on-screen rotation)

### ISSUE THREAD

**Issue by davirec** [babydots/babydots#61]
When I perform these sequences of events, the music stops playing after on-screen rotation:
1. Go to the Main activity
2. Tap in sound (sound button icon)
3. A fragment similar to this will appear:

Before rotation:
<img src="https://user-images.githubusercontent.com/3637419/157118518-48de3571-908d-4394-88b2-60d0091de67e.png" width=30% height=30%>

5. Force the pause from the activity and then return to the activity (double rotation). Note that the music stops playing. Note: the pause from activity can be performed in several ways. We suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.

The expected behavior is the music continues playing.

However, the music stops playing.

After rotation:
<img src="https://user-images.githubusercontent.com/3637419/157118536-8e1b58d9-fcfb-446d-a067-22f303be9376.png" width=30% height=30%>

Device:
- Device: Moto G30 with OS: Android 11
- Version: 1.9.0
- Device language: English

**Comment by pserwylo** [comment]
Great catch, thanks so much for the report @davirec.

Since first writing this app, I have learnt a little more about Android lifecycle management, and think it should be pretty straightforward to resolve (specifically, by moving the music playing to a `ViewModel` instead of the activity). Will try and get it sorted soon and will post here when done.

**Comment by davirec** [comment]
Thanks
